### PR TITLE
DOC: Add some notes for using on Fedora 22.

### PR DESCRIPTION
**Pull request by charris**
Getting numpy-vendor working on Fedora 22.

### CODE REVIEW

**Comment by juliantaylor** [comment]
you could just use virtualbox on fedora, should be simpler

**Comment by charris** [comment]
Yes, and my natural aversion to virtualbox and needing to get it from Oracle kicked in. In any case, I think libvirt is the default for modern (as opposed to Debian ;) versions of vagrant.

**Comment by charris** [comment]
I did run into a problem with Python 3.4, the old missing vcvarsall.bat problem. Not sure how to fix that.
```
[192.168.121.189:22] out:   File "C:\Python34\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
[192.168.121.189:22] out: 
[192.168.121.189:22] out:     raise DistutilsPlatformError("Unable to find vcvarsall.bat")
[192.168.121.189:22] out: 
[192.168.121.189:22] out: distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
```

**Comment by rgommers** [comment]
Okay, this can't hurt so in it goes. Thanks @charris.

For future readers: the ``distutils`` issue was resolved, see http://numpy-discussion.10968.n7.nabble.com/Numpy-vendor-vcvarsall-bat-problem-td40758.html

**Pull request merged**
